- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Update packages
  apt:
    update_cache: yes

- name: Install basic tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "man"
    - "less"
    - "vim"

- name: Remove root password
  shell: "passwd -d root"
