- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Update packages
  apt:
    update_cache: yes

- name: Install basic tools
  apt:
    state: present
    name:
      - man
      - less
      - vim

- name: Remove root password
  shell: passwd -d root

- name: Create user
  user:
    name: "{{ user }}"
    groups:
      - sudo
    state: present
    shell: /bin/bash
