- name: Update inputrc
  copy:
    src: files/inputrc
    dest: /home/{{ user }}/.inputrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Update bash_aliases
  copy:
    src: files/bash_aliases
    dest: /home/{{ user }}/.bash_aliases
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Copy scripts for showing last logins
  copy:
    src: files/last_logins.sh
    dest: /home/{{ user }}/.last_logins.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744

- name: Set last_logins script to execute on login
  lineinfile:
    path: /home/{{ user }}/.profile
    line: $HOME/.last_logins.sh
